---
title: "Lab 8b"
author: "Margarita Alfaro"
date: "3/17/2022"
output: 
  html_document:
  toc: TRUE
  toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../output', warning = FALSE, message = FALSE)
```

### Introduction ###
The purpose of this lab is to create a function using the Palmer penguins data set/package.

# Load libraries 
```{r}
library(tidyverse)
library(here)
library(palmerpenguins)
library(showtext)
library(PNWColors)
```

# Load/view data
```{r}
glimpse(penguins)
view(penguins)
```

# Data analysis
```{r}
#creating functions
flipper_length_cm <-(penguins $ flipper_length_mm)/10 #converts mm to cm
#function 1
flipper_mm_to_cm <- function(flipper_length_mm) {
  flipper_length_cm <- (penguins $ flipper_length_mm)/10
  return(flipper_length_cm)}
```

```{r}
#test the function
flipper_mm_to_cm(181)
```

# Plot the function

```{r, echo = FALSE}
font_add(family = "baskerville", regular = "Baskerville.ttc")
showtext_auto()
```


```{r}
#function 2
#function for plot
colpal <-pnw_palette("Sailboat",6, type = "discrete") # my color palette
ggplot(na.omit(penguins), aes(x = species, 
             y= flipper_length_mm,
             color = species,
             fill = species))+
  geom_violin(trim = FALSE, #shows distribution, keeps tails
              alpha = 0.5, #transparent background
              adjust = 0.3)+ #closer distribution
  labs(x = "Species", #x axis
       y = "Flipper Length (mm)", #y axis
       title = "Penguin species and relative flipper length", #adds title
       caption = "Source: Palmer Station LTER/PalmerPenguins package")+ #adds caption
  scale_color_manual("Species", values = colpal)+
  scale_fill_manual("Species", values = colpal)+
  theme_light()+
  theme(axis.title = element_text(size = 15), #changes axis title size
        plot.title = element_text(size = 20), #changes title size
        text = element_text(family = "baskerville")) #adds font
```

```{r}
#name the function
pengplot <- function(data, x, y){
  colpal <-pnw_palette("Sailboat",6, type = "discrete") # my color palette
ggplot(na.omit(penguins), aes(x = species, 
             y= flipper_length_mm,
             color = species,
             fill = species))+
  geom_violin(trim = FALSE, #shows distribution, keeps tails
              alpha = 0.5, #transparent background
              adjust = 0.3)+ #closer distribution
  labs(x = "Species", #x axis
       y = "Flipper Length (mm)", #y axis
       title = "Penguin species and relative flipper length", #adds title
       caption = "Source: Palmer Station LTER/PalmerPenguins package")+ #adds caption
  scale_color_manual("Species", values = colpal)+
  scale_fill_manual("Species", values = colpal)+
  theme_light()+
  theme(axis.title = element_text(size = 15), #changes size axis title
        plot.title = element_text(size = 20), #changes size of the title
        text = element_text(family = "baskerville"))} #adds font
```


```{r}
pengplot <- function(data, x, y){
  colpal <-pnw_palette("Sailboat",6, type = "discrete") # my color palette
ggplot(na.omit(penguins), aes(x = {{x}}, 
             y= {{y}},
             color = species,
             fill = species))+
  geom_violin(trim = FALSE, #shows distribution
              alpha = 0.5, #transparent background
              adjust = 0.3)+ #closer distribution
  labs(x = "Species", #x axis
       y = "Flipper Length (mm)", #y axis
       title = "Penguin species and relative flipper length", #adds title
       caption = "Source: Palmer Station LTER/PalmerPenguins package")+ #adds caption
  scale_color_manual("Species", values = colpal)+
  scale_fill_manual("Species", values = colpal)+
  theme_light()+
  theme(axis.title = element_text(size = 15), #changes size of axis title
        plot.title = element_text(size = 20), #changes size of the title
        text = element_text(family = "baskerville"))} #adds font
```


```{r, fig.align='center'}
#test the plot
pengplot (data = penguins, x = species, y = flipper_length_mm)
ggsave(here("week_8/output","func_for_peng.png"))
```