---
title: "Maps Part 1"
author: "Margarita Alfaro"
date: "3/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Libraries
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapproj)
library(mapdata)
```

#Load Data
```{r}
popdata<-read_csv(here("Week_7","data","CApopdata.csv"))


stars<-read_csv(here("Week_7","data","stars.csv"))
```

```{r}
world<-map_data("world")
head(world)
```
#get data for the USA
```{r}
usa<-map_data("usa")
head(usa)
```
#get data fro italy
```{r}
italy<-map_data("italy")
head(italy)
```
#get data for states
```{r}
states<-map_data("state")
head(states)
```
#get data for counties
```{r}
counties<-map_data("county")
head(counties)
```
```{r}
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black") +
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "mercator",
xlim = c(-180, 180))

```

```{r}
CA_data<-states %>%
  filter(region == "california") 


  ggplot()+
  geom_polygon(data = CA_data,
               aes(x = long,
                   y = lat,
                   group = group),
               color = "black")+
  coord_map()+
  theme_void()
```


```{r}
head(counties)[1:3,]
head(popdata)

CApop_county<-popdata %>%
  select("subregion" = County, Population) %>%
  inner_join(counties) %>%
  filter(region == "california")
head(CApop_county)
```
```{r}
ggplot()+
  geom_polygon(data = CApop_county,
               aes(x = long,
                   y = lat,
                   group = group,
                   fill = Population),
               color = "black")+
  geom_point(data = stars, #adds a point at all my sites
             aes(x = long,
                 y = lat,
                 size = star_no))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2")
ggsave(here("Week_7","output", "CApop.pdf"))
```

