---
title: "Maps"
author: "Margarita Alfaro"
date: "3/10/2022"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---
#ADD DESCRIPTION
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = '../output/', warning = FALSE, message = FALSE)
```

```{r}
library(ggmap)
library(tidyverse)
library(here)
library(ggsn)
library(ggplot2)
```


```{r}
library("ggmap")
```

```{r}
ChemData<-read_csv(here("Week_7","data","chemicaldata_maunalua.csv"))

glimpse(ChemData)
```


```{r}
Oahu<-get_map("Oahu")
```


```{r}
WP<-data.frame(lon = -157.7621, lat = 21.27427)

Map1<-get_map(WP)

ggmap(Map1)
```
```{r}
Map1<-get_map(WP,zoom = 17)
ggmap(Map1)
```

```{r}
Map1<-get_map(WP,zoom = 17, maptype = "satellite")
ggmap(Map1)
```

```{r}
Map1<-get_map(WP,zoom = 17, maptype = "watercolor")
ggmap(Map1)
```

```{r}
Map1<-get_map(WP,zoom = 17, maptype = "satellite") 
ggmap(Map1)+
  geom_point(data = ChemData,
             aes(x = Long, y = Lat, color = Salinity),
             size = 4) +
  scale_color_viridis_c()+
  scalebar( x.min = -157.766, x.max = -157.758,
           y.min = 21.2715, y.max = 21.2785,
            dist = 250, dist_unit = "m", model = "WGS84", 
            transform = TRUE, st.color = "white",
            box.fill = c("yellow", "white"))
```
```{r}
geocode("the white house")
```
```{r}
geocode("California State University, Northridge")
```

```{r}
library(emojifont)
search_emoji('smile')
```


```{r}
ggplot() + 
  geom_emoji('smile_cat', 
             x=1:5, y=1:5, 
             size=10)
```

